export default [
    "Web development",
    "Cyber Security",
    "Pashto",
    "AWS",
    "Cloud",
    "Bicycle riding",
    "Rally fighter",
    "Motocross",
    "Concrete",
    "Army",
    "Military",
    "Sigint",
    "Raspberry pi",
    "Accessibility",
    "Hiking",
    "Edge computing",
    "Comedy",
    "Tiny living",
    "Ultralight",
    "Web development",
    "Linux",
    "The thing to your left",
    "git"
  ]